# Generated by Django 4.0.6 on 2022-08-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='photo_book',
            new_name='photos_book',
        ),
    ]
